config/routes.rb
Rails.application.routes.draw do

  root 'pictures#index'

  resources :pictures

end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_url
  end

  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to pictures_url
    else
      render :new
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])

    if @picture.update_attributes(picture_params)
      #redirect_to "/pictures/#{@picture.id}"
      redirect_to picture_path(@picture)
    else
      render :edit
      #needs to have render (page) or else it would attempt to auto-render back to its method page
      #which is :update, and that doesn't exist, so it will return an error
    end
  end

  private # anything after this is not going to be processed on front end, for security reasons
  # if anyone had access to this they could change your database

  def picture_params
    params.require(:picture).permit(:artist, :title, :url)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>

<p>
  <%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>

  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/pictures/index.html.erb
<h1>Pictures (<%= @pictures.length %>)</h1>

<form class = "new_pic_button" action='/pictures/new'>
  <input type='hidden' name='_method' value='put'>
  <input type='submit' value='New Picture'>
</form>

<!-- <%= link_to "New Picture", "/pictures/new" %><br> -->


<% @pictures.each do |picture| %>
  <%= link_to image_tag(picture.url), "picture_path(picture)" %>
  <p><%= picture.title %>, <%= picture.artist %></p>
<% end %>

app/views/pictures/new.html.erb
<h1>Add a picture</h1>
<%= link_to "Back to Pictures", pictures_url %>

<%= form_for @picture do |f| %>
  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/pictures/show.html.erb
<div class = "picture_page">

<%= link_to "Back to Pictures", pictures_url %>
<%= button_to "Edit", edit_picture_path(@picture) %>
<%= button_to "Delete", @picture, method: :delete, data: {confirm: "Are you sure you want to delete this picture?"} %>



<br>
<br>
<p>Title: <%= @picture.title %></p><br>
<p>Artist: <%= @picture.artist %></p>
<br>
<br>
<%= image_tag @picture.url %>

</div>